import numpy as np

FACE_U, FACE_D, FACE_F, FACE_B, FACE_L, FACE_R = range(6)
FACE_NAMES = ['U', 'D', 'F', 'B', 'L', 'R']

COLOR_WHITE = 1
COLOR_YELLOW = 2
COLOR_GREEN = 3
COLOR_BLUE = 4
COLOR_ORANGE = 5
COLOR_RED = 6

COLOR_LETTER_TO_CODE = {
    'w': COLOR_WHITE,
    'y': COLOR_YELLOW,
    'g': COLOR_GREEN,
    'b': COLOR_BLUE,
    'o': COLOR_ORANGE,
    'r': COLOR_RED,
}

DEFAULT_FACE_COLOR = {
    FACE_U: COLOR_WHITE,
    FACE_D: COLOR_YELLOW,
    FACE_F: COLOR_GREEN,
    FACE_B: COLOR_BLUE,
    FACE_L: COLOR_ORANGE,
    FACE_R: COLOR_RED,
}

CORNER_UFR = 0
CORNER_URB = 1
CORNER_UBL = 2
CORNER_ULF = 3
CORNER_DFR = 4
CORNER_DRB = 5
CORNER_DBL = 6
CORNER_DLF = 7

EDGE_UF = 0
EDGE_UR = 1
EDGE_UB = 2
EDGE_UL = 3
EDGE_FR = 4
EDGE_RB = 5
EDGE_BL = 6
EDGE_LF = 7
EDGE_DF = 8
EDGE_DR = 9
EDGE_DB = 10
EDGE_DL = 11

CORNER_NAMES = ['UFR', 'URB', 'UBL', 'ULF', 'DFR', 'DRB', 'DBL', 'DLF']
EDGE_NAMES = ['UF', 'UR', 'UB', 'UL', 'FR', 'RB', 'BL', 'LF', 'DF', 'DR', 'DB', 'DL']

CORNER_COLOR_SETS = {
    CORNER_UFR: {COLOR_WHITE, COLOR_GREEN, COLOR_RED},
    CORNER_URB: {COLOR_WHITE, COLOR_RED, COLOR_BLUE},
    CORNER_UBL: {COLOR_WHITE, COLOR_BLUE, COLOR_ORANGE},
    CORNER_ULF: {COLOR_WHITE, COLOR_ORANGE, COLOR_GREEN},
    CORNER_DFR: {COLOR_YELLOW, COLOR_GREEN, COLOR_RED},
    CORNER_DRB: {COLOR_YELLOW, COLOR_RED, COLOR_BLUE},
    CORNER_DBL: {COLOR_YELLOW, COLOR_BLUE, COLOR_ORANGE},
    CORNER_DLF: {COLOR_YELLOW, COLOR_ORANGE, COLOR_GREEN},
}

EDGE_COLOR_SETS = {
    EDGE_UF: {COLOR_WHITE, COLOR_GREEN},
    EDGE_UR: {COLOR_WHITE, COLOR_RED},
    EDGE_UB: {COLOR_WHITE, COLOR_BLUE},
    EDGE_UL: {COLOR_WHITE, COLOR_ORANGE},
    EDGE_FR: {COLOR_GREEN, COLOR_RED},
    EDGE_RB: {COLOR_RED, COLOR_BLUE},
    EDGE_BL: {COLOR_BLUE, COLOR_ORANGE},
    EDGE_LF: {COLOR_ORANGE, COLOR_GREEN},
    EDGE_DF: {COLOR_YELLOW, COLOR_GREEN},
    EDGE_DR: {COLOR_YELLOW, COLOR_RED},
    EDGE_DB: {COLOR_YELLOW, COLOR_BLUE},
    EDGE_DL: {COLOR_YELLOW, COLOR_ORANGE},
}

# Sticker coordinates are (face, row, col) using 0-indexed rows/cols.
CORNER_STICKER_POSITIONS = {
    CORNER_UFR: [(FACE_U, 2, 2), (FACE_F, 0, 2), (FACE_R, 0, 0)],
    CORNER_URB: [(FACE_U, 0, 2), (FACE_R, 0, 2), (FACE_B, 0, 0)],
    CORNER_UBL: [(FACE_U, 0, 0), (FACE_B, 0, 2), (FACE_L, 0, 0)],
    CORNER_ULF: [(FACE_U, 2, 0), (FACE_L, 0, 2), (FACE_F, 0, 0)],
    CORNER_DFR: [(FACE_D, 0, 2), (FACE_F, 2, 2), (FACE_R, 2, 0)],
    CORNER_DRB: [(FACE_D, 2, 2), (FACE_R, 2, 2), (FACE_B, 2, 0)],
    CORNER_DBL: [(FACE_D, 2, 0), (FACE_B, 2, 2), (FACE_L, 2, 0)],
    CORNER_DLF: [(FACE_D, 0, 0), (FACE_L, 2, 2), (FACE_F, 2, 0)],
}

EDGE_STICKER_POSITIONS = {
    EDGE_UF: [(FACE_U, 2, 1), (FACE_F, 0, 1)],
    EDGE_UR: [(FACE_U, 1, 2), (FACE_R, 0, 1)],
    EDGE_UB: [(FACE_U, 0, 1), (FACE_B, 0, 1)],
    EDGE_UL: [(FACE_U, 1, 0), (FACE_L, 0, 1)],
    EDGE_FR: [(FACE_F, 1, 2), (FACE_R, 1, 0)],
    EDGE_RB: [(FACE_R, 1, 2), (FACE_B, 1, 0)],
    EDGE_BL: [(FACE_B, 1, 2), (FACE_L, 1, 0)],
    EDGE_LF: [(FACE_L, 1, 2), (FACE_F, 1, 0)],
    EDGE_DF: [(FACE_D, 0, 1), (FACE_F, 2, 1)],
    EDGE_DR: [(FACE_D, 1, 2), (FACE_R, 2, 1)],
    EDGE_DB: [(FACE_D, 2, 1), (FACE_B, 2, 1)],
    EDGE_DL: [(FACE_D, 1, 0), (FACE_L, 2, 1)],
}

MOVE_TOKENS = ['R', "R'", 'R2', 'L', "L'", 'L2', 'U', "U'", 'U2', 'D', "D'", 'D2', 'F', "F'", 'F2', 'B', "B'", 'B2']


WHITE_CROSS_EDGES = [EDGE_UF, EDGE_UR, EDGE_UL, EDGE_UB]
YELLOW_CROSS_EDGES = [EDGE_DF, EDGE_DR, EDGE_DL, EDGE_DB]
GREEN_CROSS_EDGES = [EDGE_UF, EDGE_FR, EDGE_DF, EDGE_LF]
BLUE_CROSS_EDGES = [EDGE_UB, EDGE_RB, EDGE_DB, EDGE_BL]
ORANGE_CROSS_EDGES = [EDGE_UL, EDGE_BL, EDGE_DL, EDGE_FR]
RED_CROSS_EDGES = [EDGE_UR, EDGE_FR, EDGE_DR, EDGE_RB]

WHITE_CROSS_EDGES_POSITIONS = [0, 1, 2, 3]
YELLOW_CROSS_EDGES_POSITIONS = [8, 9, 10, 11]
GREEN_CROSS_EDGES_POSITIONS = [0, 4, 8, 7]
BLUE_CROSS_EDGES_POSITIONS = [2, 5, 10, 6]
ORANGE_CROSS_EDGES_POSITIONS = [3, 6, 11, 4]
RED_CROSS_EDGES_POSITIONS = [1, 4, 9, 5]
